/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   Atelier : Tout comprendre au Plug & Charge avec Chargemap (Automobile Propre)
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "plug-charge-b2-v3-bis",
    "lien": "https://orionside.github.io/Atelier_Plug_Charge_B2_v3_bis/",
    "titre": "Plug & Charge",
    "niveau": "B2",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "Expliquer simplement… et vérifier qu'on s'est compris",
    "objectif": "Aujourd'hui, vous apprenez à <strong>expliquer quelque chose de compliqué avec des mots simples</strong>, puis à <strong>vérifier que l'autre a bien compris</strong>. En 1 minute, sans chercher vos mots.",
    "video": {
      "url": "https://youtu.be/AzsqYl61jqA",
      "titre": "Tout comprendre au Plug & Charge avec Chargemap ! (Automobile Propre)",
      "duree": "7 min"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (7 min)",
        "url": "https://youtu.be/AzsqYl61jqA"
      },
      {
        "label": "Lire l'article d'Automobile Propre sur le Plug & Charge",
        "url": "https://www.automobile-propre.com/articles/plug-and-charge-la-recharge-des-vehicules-electriques-se-simplifie-drastiquement"
      }
    ]
  },
  "sujet": {
    "lieu": "Au bureau, à la machine à café",
    "qui": "Un nouveau collègue",
    "dit": "« On m'a parlé du nouvel outil de signature électronique. Tu peux m'expliquer simplement comment ça marche ? »",
    "vous": "Vous connaissez bien cet outil. Expliquez simplement, étape par étape, puis vérifiez qu'il a bien compris.",
    "consigne": "Expliquez-lui.",
    "perso": {
      "question": "Dans votre entreprise, qu'est-ce que vous pourriez expliquer à un nouveau collègue ?",
      "exemple": "ex. : un logiciel, une procédure, un projet, un service",
      "phrase": "Un nouveau collègue vous demande de lui expliquer simplement : {x}. Expliquez étape par étape, puis vérifiez qu'il a bien compris."
    },
    "plan": [
      {
        "titre": "Le principe",
        "aide": "L'idée, c'est que…"
      },
      {
        "titre": "Comment faire",
        "aide": "Il suffit de…"
      },
      {
        "titre": "Une différence",
        "aide": "Ce n'est pas tout à fait la même chose que…"
      },
      {
        "titre": "Vérifier",
        "aide": "On est bien d'accord que… ?"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Mon explication était trop compliquée",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Le Plug & Charge en 40 secondes",
      "debut": 39.18,
      "fin": 77.72,
      "pourquoi": "Le directeur technique explique une technologie compliquée avec des mots simples. C'est ce que vous allez faire.",
      "devine": "« Plug » = brancher, « charge » = recharger. À votre avis, que fait le <strong>Plug & Charge</strong> quand on branche une voiture électrique ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Avec le Plug & Charge, que se passe-t-il quand on branche la voiture ?",
          "options": [
            "Il faut payer avec une carte bancaire.",
            "La recharge démarre toute seule, sans carte.",
            "Il faut appeler l'opérateur."
          ],
          "bonne": 1,
          "explication": "La borne récupère l'identifiant installé dans la voiture, demande l'autorisation, et « la charge démarre » sans passer de carte."
        },
        {
          "q": "Selon lui, cette recharge est plus…",
          "options": [
            "chère et plus lente.",
            "compliquée, mais plus rapide.",
            "simple et plus sûre."
          ],
          "bonne": 2,
          "explication": "« Une expérience beaucoup plus <strong>fluide</strong> de recharge, et beaucoup plus intéressante d'un point de vue <strong>sécurité</strong>. »"
        }
      ],
      "trous": [
        {
          "avant": "C'est un nouveau protocole de",
          "apres": "entre, d'un côté, le véhicule et, de l'autre, les bornes.",
          "aide": "= échange d'informations",
          "reponses": [
            "communication"
          ],
          "solution": "communication"
        },
        {
          "avant": "C'est une expérience beaucoup plus",
          "apres": "de recharge.",
          "aide": "= simple, sans blocage",
          "reponses": [
            "fluide"
          ],
          "solution": "fluide"
        }
      ],
      "difficile": {
        "debut": 42.7,
        "fin": 47.23,
        "texte": "Anglais, sigle et chiffres arrivent très vite : « Plug and Charge, ou plutôt, d'un point de vue technique, ISO 15118 ». Pas besoin de tout comprendre. Retenez l'expression utile : <strong>d'un point de vue technique</strong> (= si on regarde la technique)."
      }
    },
    {
      "id": "B",
      "titre": "« Une usine à gaz » ?",
      "debut": 77.67,
      "fin": 114.61,
      "pourquoi": "Le journaliste reformule pour vérifier qu'il a compris, puis pose une question. Vous allez faire la même chose.",
      "devine": "Le journaliste pense que, derrière cette simplicité, le système est très compliqué. À votre avis, pourquoi ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Pourquoi le journaliste pense-t-il que c'est compliqué ?",
          "options": [
            "Parce que les voitures électriques sont lentes.",
            "Parce qu'il y a des bornes, des réseaux, des marques et des modèles de voitures différents.",
            "Parce que l'application est payante."
          ],
          "bonne": 1,
          "explication": "« Il y a des bornes qui sont différentes, des réseaux de recharge différents, des marques de voitures différentes, des modèles de voitures différents. »"
        },
        {
          "q": "Que veut dire « une usine à gaz » ici ?",
          "options": [
            "Une usine qui produit du gaz.",
            "Un système beaucoup trop compliqué.",
            "Une borne de recharge."
          ],
          "bonne": 1,
          "explication": "<strong>Une usine à gaz</strong> = un système trop compliqué. Une expression très courante au bureau."
        }
      ],
      "trous": [
        {
          "avant": "Parce que, si j'ai bien",
          "apres": ", il faut que la voiture discute avec la borne.",
          "aide": "participe passé de « comprendre »",
          "reponses": [
            "compris"
          ],
          "solution": "compris"
        },
        {
          "avant": "Ça me semble être une",
          "apres": "à gaz absolument extraordinaire.",
          "aide": "= un grand bâtiment où l'on fabrique quelque chose",
          "reponses": [
            "usine"
          ],
          "solution": "usine"
        }
      ],
      "difficile": {
        "debut": 109.05,
        "fin": 114.61,
        "texte": "« Ça me semble être une usine à gaz absolument extraordinaire. À quel point c'est un challenge pour Chargemap, du coup ? » <strong>Du coup</strong> = donc : à l'oral, on l'entend partout. <strong>Un challenge</strong> = un défi (mot anglais très utilisé en entreprise)."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour présenter le principe",
      "forme": "L'idée, c'est que…",
      "film": {
        "texte": "Et <strong>l'idée, finalement, c'est qu'</strong>on va installer votre identifiant Chargemap dans le véhicule.",
        "t": 53,
        "debut": 52.92,
        "fin": 58.35,
        "contour": [
          -2.8,
          -2.2,
          -0.2,
          3.0,
          2.3,
          0.3,
          0.6,
          0.8,
          2.2,
          5.2,
          5.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1.6,
          0.9,
          -0.4,
          -1.3,
          -1.6,
          -2.1,
          -2.0,
          -0.4,
          1.6,
          0.1,
          -1.4,
          -2.8,
          -4.3,
          -5.0,
          -4.3,
          -3.7,
          -4.8,
          -5.4,
          -2.8,
          -2.4,
          2.9,
          3.1,
          3.2,
          3.3,
          3.3,
          3.4,
          2.1,
          0.8,
          -0.1,
          -0.5,
          -0.1,
          0.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.1,
          -4.2,
          -0.3,
          6.4,
          7.4,
          6.7,
          6.1,
          5.4,
          3.6,
          2.1,
          1.9,
          1.6,
          0.1,
          -0.4,
          1.5,
          0.8,
          0.3,
          -0.1,
          -0.6,
          -1.0,
          -1.6,
          -2.0,
          -2.4,
          -2.9,
          -3.3,
          -3.8,
          -3.4,
          -3.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -4.1,
          -4.4,
          -4.9,
          -1.4,
          3.7,
          5.8,
          6.9,
          6.4,
          2.9,
          0.7,
          -0.8,
          -2.7,
          -5.2,
          -7.1,
          -6.6,
          -6.1,
          -5.6,
          -5.0,
          -1.4,
          1.8,
          1.6,
          -0.5
        ],
        "etendue": 11.2
      },
      "exemple": "L'idée, c'est que chaque client signe en ligne, sans imprimer le contrat.",
      "detect": [
        "l idee c est",
        "l idee finalement c est"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour montrer que c'est simple",
      "forme": "Il suffit de…",
      "film": {
        "texte": "<strong>Il suffit d'</strong>aller dans l'application Chargemap, de lancer le menu Plug and Charge.",
        "t": 141,
        "debut": 140.49,
        "fin": 144.7,
        "contour": [
          2.8,
          2.3,
          1.1,
          1.7,
          1.6,
          1.7,
          1.6,
          1.5,
          1.4,
          0.6,
          0.5,
          1.1,
          0.8,
          0.5,
          0.1,
          -0.4,
          -1.0,
          -1.2,
          -0.9,
          -0.6,
          -0.4,
          -0.1,
          0.2,
          -0.8,
          -1.4,
          -1.9,
          -1.9,
          -1.9,
          -1.9,
          -1.9,
          -2.4,
          -3.1,
          -3.0,
          -3.0,
          -2.9,
          -2.8,
          -3.5,
          -4.2,
          -3.2,
          -2.9,
          -2.4,
          -2.5,
          -2.5,
          -2.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.5,
          -3.8,
          -4.4,
          -2.7,
          -0.3,
          0.6,
          0.8,
          1.0,
          0.7,
          0.2,
          -0.3,
          -1.1,
          -0.5,
          0.0,
          0.6,
          1.2,
          0.7,
          0.1,
          -0.0,
          0.0,
          0.2,
          0.2,
          0.6,
          0.7,
          0.8,
          1.1,
          1.4,
          1.5,
          1.6,
          2.0,
          2.0,
          1.8,
          1.0,
          -0.3,
          -1.8,
          -2.3,
          -3.0,
          -3.6,
          -4.0,
          -2.9,
          -1.8,
          -0.7,
          0.4,
          -0.8,
          -1.7,
          -1.9,
          -2.0,
          -2.4,
          -3.0,
          -2.9,
          -3.3,
          -3.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2.9,
          3.1,
          1.7,
          -0.9,
          -3.3,
          -4.1,
          -4.3
        ],
        "etendue": 6.1
      },
      "exemple": "Il suffit d'ouvrir le document, de cliquer sur « Signer », et c'est fini.",
      "detect": [
        "il suffit de",
        "il suffit d"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour reformuler ce que l'autre a dit",
      "forme": "Si j'ai bien compris, …",
      "film": {
        "texte": "Parce que, <strong>si j'ai bien compris</strong>, il faut que la voiture discute avec la borne, qui discute avec l'opérateur, et qui, après, interagit à nouveau avec la voiture.",
        "t": 88,
        "debut": 87.43,
        "fin": 97.91,
        "contour": [
          -1.1,
          -0.7,
          -0.2,
          0.9,
          2.1,
          3.2,
          2.5,
          2.1,
          -0.2,
          -1.1,
          -2.4,
          -3.7,
          5.4,
          9.1,
          8.1,
          7.0,
          6.0,
          5.0,
          4.0,
          2.9,
          1.9,
          0.6,
          1.3,
          -0.1,
          -2.6,
          0.8,
          -0.2,
          4.3,
          -4.3,
          -3.0,
          -1.6,
          -0.3,
          0.7,
          0.3,
          -0.2,
          -2.3,
          -0.5,
          1.2,
          0.2,
          -1.1,
          -3.8,
          -3.5,
          -3.1,
          -3.6,
          -0.2,
          -0.2,
          2.8,
          1.5,
          0.0,
          -1.5,
          -2.6,
          -3.3,
          -3.0,
          -2.6,
          -3.4,
          -2.3,
          2.1,
          1.4,
          0.1,
          -2.0,
          1.9,
          0.4,
          -0.3,
          0.2,
          0.7,
          1.2,
          0.4,
          -2.0,
          -2.4,
          -2.9,
          -3.3,
          -3.7,
          -3.3,
          -2.8,
          -3.8,
          -2.8,
          -1.8,
          -0.7,
          0.3,
          -2.1,
          -2.8,
          -0.9,
          -2.5,
          -4.9,
          -4.8,
          -0.6,
          3.5,
          6.8,
          9.9,
          10.5,
          7.9,
          5.3,
          2.7,
          0.1,
          0.2,
          -0.2,
          0.8,
          1.5,
          3.0,
          4.3,
          3.9,
          -2.1,
          12.0,
          9.4,
          6.9,
          4.3,
          4.9,
          2.4,
          -1.0,
          -0.6,
          -1.1,
          2.5,
          1.7,
          0.3,
          2.7,
          0.8,
          0.2,
          -0.5,
          -0.4,
          0.4
        ],
        "etendue": 13.1
      },
      "exemple": "Si j'ai bien compris, le client signe en ligne, et nous recevons le contrat tout de suite.",
      "detect": [
        "si j ai bien compris",
        "si je comprends bien"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour vérifier un point important",
      "forme": "On est bien d'accord que… ?",
      "film": {
        "texte": "D'accord, mais <strong>on est bien d'accord que</strong> cette manipulation de rentrer le VIN et tout ça, tu le fais une fois… au tout début ? <em>(En même temps, l'autre répond : « Exactement. »)</em>",
        "t": 174,
        "debut": 173.44,
        "fin": 180.96,
        "contour": [
          -1.0,
          -0.8,
          -2.5,
          -2.3,
          -2.1,
          -1.8,
          -1.6,
          -1.4,
          -1.8,
          -2.2,
          -2.5,
          -1.9,
          -2.4,
          -1.7,
          -1.7,
          -2.0,
          -3.2,
          4.1,
          3.5,
          1.4,
          -0.7,
          -2.1,
          -2.9,
          1.1,
          1.3,
          1.8,
          0.9,
          0.4,
          0.8,
          0.2,
          2.9,
          -0.2,
          -2.2,
          -0.5,
          1.3,
          1.2,
          1.0,
          0.7,
          0.7,
          0.7,
          0.4,
          -0.5,
          -0.4,
          -2.9,
          -4.2,
          -2.6,
          -0.6,
          -0.5,
          -0.1,
          0.3,
          0.4,
          0.3,
          4.1,
          11.6,
          -2.4,
          -2.8,
          -3.1,
          -3.4,
          -4.4,
          -3.6,
          -2.8,
          -2.0,
          -2.8,
          -3.5,
          0.0,
          -0.6,
          -1.4,
          -2.6,
          -1.4,
          0.2,
          0.4,
          0.6,
          -0.5,
          -1.7,
          -2.1,
          -2.6,
          -3.0,
          -3.8,
          0.9,
          5.6,
          6.9,
          6.4,
          5.4,
          3.5,
          1.4,
          -2.2,
          0.7,
          4.6,
          12.0,
          5.8,
          4.7,
          4.1,
          2.2,
          2.7,
          3.2,
          2.3,
          -0.4,
          -1.4,
          -1.9,
          -2.4,
          -2.9,
          -3.4,
          -3.5,
          -1.1,
          -0.2,
          -0.4,
          -1.8,
          -3.2,
          -0.9,
          5.8,
          2.9,
          4.1,
          2.4,
          -0.4,
          -1.1,
          -2.1,
          1.0,
          6.2,
          11.2,
          12.0
        ],
        "etendue": 10.7
      },
      "exemple": "On est bien d'accord que je signe une seule fois, et que le client reçoit une copie ?",
      "detect": [
        "on est bien d accord",
        "on est d accord"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour demander une précision",
      "forme": "Quelle est la différence avec… ?",
      "film": {
        "texte": "Alors je pense qu'il y a tout un pan de nos spectateurs qui vont se dire : « Mais enfin, chez Tesla, ça existe depuis des années. » <strong>Quelle est la différence avec</strong> ce que fait Tesla, du coup ?",
        "t": 202,
        "debut": 195.95,
        "fin": 205.69,
        "contour": [
          -1.5,
          -3.0,
          7.5,
          6.0,
          0.8,
          -1.7,
          10.3,
          10.1,
          8.3,
          5.1,
          2.8,
          1.2,
          5.3,
          4.1,
          2.3,
          0.2,
          -0.5,
          2.3,
          5.0,
          0.5,
          -0.5,
          -0.4,
          -0.3,
          -2.2,
          0.4,
          -0.1,
          1.0,
          2.0,
          1.2,
          0.0,
          -0.6,
          -1.2,
          -2.7,
          -2.2,
          -2.1,
          -2.3,
          -1.5,
          -0.8,
          -0.0,
          -1.0,
          2.5,
          2.6,
          0.2,
          8.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.9,
          -1.9,
          -3.1,
          0.2,
          -0.2,
          -0.5,
          -2.5,
          -3.6,
          -2.0,
          -0.5,
          -1.7,
          -1.2,
          -2.5,
          -1.3,
          -0.1,
          -1.2,
          -2.4,
          -3.5,
          -2.8,
          -3.1,
          -2.8,
          -1.9,
          -1.1,
          -3.2,
          -2.1,
          -2.0,
          2.3,
          7.1,
          12.0,
          8.3,
          7.7,
          7.1,
          6.5,
          6.1,
          5.4,
          2.5,
          1.9,
          3.8,
          3.2,
          2.7,
          2.2,
          5.3,
          8.1,
          6.8,
          5.6,
          4.3,
          3.0,
          1.8,
          0.5,
          0.1,
          1.3,
          3.3,
          2.2,
          1.1,
          -0.0,
          -0.9,
          -1.8,
          0.9,
          0.5,
          0.6,
          -0.6,
          -0.3,
          -1.7,
          -1.6,
          -1.6,
          -2.6,
          -3.0,
          -3.1,
          -3.2
        ],
        "etendue": 12.8
      },
      "exemple": "Quelle est la différence avec l'ancien système, du coup ?",
      "detect": [
        "quelle est la difference avec",
        "quelle est la difference"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour corriger poliment (à l'oral, on dit souvent « c'est pas » au lieu de « ce n'est pas »)",
      "forme": "Ce n'est pas tout à fait la même chose.",
      "film": {
        "texte": "Non, <strong>c'est pas tout à fait la même chose</strong>.",
        "t": 274,
        "debut": 273.66,
        "fin": 276.3,
        "contour": [
          0.0,
          -0.3,
          -1.0,
          -1.8,
          -2.3,
          -2.6,
          -3.1,
          -3.6,
          -4.5,
          -5.2,
          -5.8,
          -4.9,
          -4.0,
          -3.0,
          -2.1,
          -1.2,
          -0.3,
          0.3,
          0.7,
          1.3,
          2.2,
          3.2,
          3.6,
          3.8,
          3.7,
          3.3,
          2.2,
          1.1,
          -0.0,
          -1.1,
          -1.9,
          -3.1,
          -4.3,
          -4.8,
          -1.0,
          2.8,
          2.8,
          2.8,
          2.5,
          1.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          0.6,
          0.4,
          -0.4,
          -1.3,
          -0.5,
          0.2,
          1.0,
          1.8,
          1.4,
          0.9,
          0.5,
          0.1,
          -0.5,
          -0.8,
          -0.7,
          -0.7,
          -0.7,
          -0.9,
          -1.1,
          -1.1,
          -1.1,
          -1.2,
          -1.7,
          -1.3,
          -0.8,
          -0.4,
          0.1,
          0.5,
          1.0,
          1.4,
          1.4,
          1.9,
          2.6,
          3.1,
          3.7,
          3.9,
          3.8,
          3.4,
          2.5,
          1.6,
          0.4,
          -0.9,
          -1.8,
          -2.0,
          -2.5,
          -3.0,
          -3.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.3,
          -2.5,
          -1.1,
          1.0,
          1.0,
          0.9,
          0.6,
          0.7,
          0.8,
          0.5,
          -2.0,
          -4.1,
          -4.1,
          -3.8
        ],
        "etendue": 7.9
      },
      "exemple": "Un devis et une facture, ce n'est pas tout à fait la même chose.",
      "detect": [
        "pas tout a fait la meme chose"
      ]
    }
  ],
  "prononciation": {
    "intro": "Pour <strong>expliquer étape par étape</strong>, le français utilise la mélodie : à la fin de chaque étape, la voix <strong>monte</strong>. Cela veut dire : « ce n'est pas fini, écoutez la suite ».",
    "regle": [
      "Découpez votre explication en étapes courtes.",
      "À la fin de chaque étape, la voix <strong>monte ↗</strong> : l'autre attend la suite.",
      "À la dernière étape, la voix <strong>ne monte plus</strong> : l'explication est finie."
    ],
    "attention": "Si votre voix descend à chaque étape, l'autre croit que vous avez fini… et il vous coupe la parole. <em>Les flèches de cette page ont été placées d'après la voix réelle de la vidéo, mesurée.</em>",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "Il y a des bornes qui sont différentes, des réseaux de recharge dif·fé·*rents, des marques de voitures dif·fé·*rentes, des modèles de voitures différents.",
        "consigne": "Le journaliste énumère 4 éléments. Écoutez : sur quelles syllabes la voix monte-t-elle nettement ? Cliquez sur les 2 syllabes, puis vérifiez.",
        "explication": "La voix monte sur « -rents » et « -rentes » (2e et 3e éléments) : la liste continue. Au dernier élément, elle ne monte plus : la liste est finie.",
        "debut": 100.2,
        "fin": 109.41
      },
      {
        "titre": "Phrase 2",
        "phrase": "Parce que si j'ai bien compris, il faut que la voiture discute avec la *borne, qui discute avec l'o·pé·ra·*teur, et qui après interagit à nouveau avec la voiture.",
        "consigne": "Cette phrase explique 3 étapes. Cliquez sur les 2 syllabes où la voix monte (fin des 2 premières étapes), puis vérifiez.",
        "explication": "« borne » ↗ et « -teur » ↗ : la voix monte, l'explication continue. À la fin (« voiture »), elle ne monte plus.",
        "debut": 87.43,
        "fin": 97.91
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte (mesuré dans la vidéo)"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "fin d'une étape"
      ]
    ],
    "modeles": [
      {
        "texte": "Il y a des bornes qui sont diffé<strong>rentes</strong> | des réseaux de recharge diffé<strong>rents</strong> ↗ | des marques de voitures diffé<strong>rentes</strong> ↗ | des modèles de voitures diffé<strong>rents</strong>",
        "t": 101,
        "debut": 100.2,
        "fin": 109.41,
        "contour": [
          0.2,
          -1.7,
          -3.5,
          -4.2,
          -4.8,
          -5.2,
          -0.4,
          3.3,
          0.6,
          -6.4,
          -5.1,
          -3.8,
          -4.5,
          -4.0,
          -4.3,
          -4.1,
          -4.3,
          -3.8,
          -3.2,
          -2.7,
          -2.1,
          -1.5,
          -1.0,
          -2.7,
          -2.3,
          -2.3,
          1.9,
          2.4,
          0.6,
          0.3,
          1.2,
          0.7,
          0.3,
          -0.2,
          1.5,
          0.3,
          -0.5,
          -0.8,
          -2.1,
          -2.9,
          -3.6,
          -3.4,
          -2.4,
          -0.2,
          2.4,
          3.0,
          1.0,
          1.1,
          1.4,
          2.2,
          1.3,
          -0.9,
          -1.2,
          -0.8,
          -0.9,
          -0.9,
          -1.7,
          2.3,
          5.9,
          7.4,
          4.7,
          1.9,
          -0.8,
          -3.6,
          -2.7,
          1.3,
          1.4,
          0.4,
          -2.0,
          0.6,
          -0.4,
          1.3,
          5.7,
          7.2,
          5.7,
          4.2,
          2.7,
          1.2,
          -0.3,
          -1.8,
          -0.8,
          -0.4,
          0.1,
          3.9,
          3.5,
          4.0,
          4.4,
          1.9,
          0.6,
          -0.2,
          3.6,
          4.5,
          0.4,
          -1.8,
          -1.2,
          0.8,
          4.8,
          4.3,
          3.8,
          6.1,
          6.1,
          4.9,
          1.6,
          -0.0,
          -1.7,
          -3.3,
          -3.5,
          0.3,
          1.2,
          1.1,
          0.3,
          0.0,
          -0.3,
          -2.6,
          -3.4,
          -4.3,
          -1.0,
          -1.0,
          5.7,
          6.1
        ],
        "etendue": 10.4
      },
      {
        "texte": "Parce que si j'ai bien com<strong>pris</strong> | il faut que la voiture discute avec la <strong>borne</strong> ↗ | qui discute avec l'opéra<strong>teur</strong> ↗ | et qui après interagit à nouveau avec la voi<strong>ture</strong>",
        "t": 88,
        "debut": 87.43,
        "fin": 97.91,
        "contour": [
          -1.1,
          -0.7,
          -0.2,
          0.9,
          2.1,
          3.2,
          2.5,
          2.1,
          -0.2,
          -1.1,
          -2.4,
          -3.7,
          5.4,
          9.1,
          8.1,
          7.0,
          6.0,
          5.0,
          4.0,
          2.9,
          1.9,
          0.6,
          1.3,
          -0.1,
          -2.6,
          0.8,
          -0.2,
          4.3,
          -4.3,
          -3.0,
          -1.6,
          -0.3,
          0.7,
          0.3,
          -0.2,
          -2.3,
          -0.5,
          1.2,
          0.2,
          -1.1,
          -3.8,
          -3.5,
          -3.1,
          -3.6,
          -0.2,
          -0.2,
          2.8,
          1.5,
          0.0,
          -1.5,
          -2.6,
          -3.3,
          -3.0,
          -2.6,
          -3.4,
          -2.3,
          2.1,
          1.4,
          0.1,
          -2.0,
          1.9,
          0.4,
          -0.3,
          0.2,
          0.7,
          1.2,
          0.4,
          -2.0,
          -2.4,
          -2.9,
          -3.3,
          -3.7,
          -3.3,
          -2.8,
          -3.8,
          -2.8,
          -1.8,
          -0.7,
          0.3,
          -2.1,
          -2.8,
          -0.9,
          -2.5,
          -4.9,
          -4.8,
          -0.6,
          3.5,
          6.8,
          9.9,
          10.5,
          7.9,
          5.3,
          2.7,
          0.1,
          0.2,
          -0.2,
          0.8,
          1.5,
          3.0,
          4.3,
          3.9,
          -2.1,
          12.0,
          9.4,
          6.9,
          4.3,
          4.9,
          2.4,
          -1.0,
          -0.6,
          -1.1,
          2.5,
          1.7,
          0.3,
          2.7,
          0.8,
          0.2,
          -0.5,
          -0.4,
          0.4
        ],
        "etendue": 13.1
      },
      {
        "texte": "Il suffit d'aller dans l'application Charge<strong>map</strong> | de lancer le menu Plug and <strong>Charge</strong> ↗",
        "t": 141,
        "debut": 140.49,
        "fin": 144.7,
        "contour": [
          2.8,
          2.3,
          1.1,
          1.7,
          1.6,
          1.7,
          1.6,
          1.5,
          1.4,
          0.6,
          0.5,
          1.1,
          0.8,
          0.5,
          0.1,
          -0.4,
          -1.0,
          -1.2,
          -0.9,
          -0.6,
          -0.4,
          -0.1,
          0.2,
          -0.8,
          -1.4,
          -1.9,
          -1.9,
          -1.9,
          -1.9,
          -1.9,
          -2.4,
          -3.1,
          -3.0,
          -3.0,
          -2.9,
          -2.8,
          -3.5,
          -4.2,
          -3.2,
          -2.9,
          -2.4,
          -2.5,
          -2.5,
          -2.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.5,
          -3.8,
          -4.4,
          -2.7,
          -0.3,
          0.6,
          0.8,
          1.0,
          0.7,
          0.2,
          -0.3,
          -1.1,
          -0.5,
          0.0,
          0.6,
          1.2,
          0.7,
          0.1,
          -0.0,
          0.0,
          0.2,
          0.2,
          0.6,
          0.7,
          0.8,
          1.1,
          1.4,
          1.5,
          1.6,
          2.0,
          2.0,
          1.8,
          1.0,
          -0.3,
          -1.8,
          -2.3,
          -3.0,
          -3.6,
          -4.0,
          -2.9,
          -1.8,
          -0.7,
          0.4,
          -0.8,
          -1.7,
          -1.9,
          -2.0,
          -2.4,
          -3.0,
          -2.9,
          -3.3,
          -3.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2.9,
          3.1,
          1.7,
          -0.9,
          -3.3,
          -4.1,
          -4.3
        ],
        "etendue": 6.1
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "boutonObjection": "Question du collègue (pour le formateur)",
    "essais": [
      {
        "duree": 90,
        "consigne": "Expliquez avec vos notes.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>L'idée, c'est que…</strong> » et « <strong>Il suffit de…</strong> ». Et faites monter la voix ↗ à la fin de chaque étape."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur joue le collègue et vous pose une question. Répondez, puis vérifiez avec : « <strong>On est bien d'accord que… ?</strong> »",
        "ajout": "Pour l'essai 3, commencez votre réponse à la question par : « <strong>Si j'ai bien compris, …</strong> »."
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel.",
        "ajout": ""
      }
    ],
    "objections": [
      "Mais concrètement, je dois faire quoi ?",
      "Quelle est la différence avec l'ancien système, du coup ?",
      "Et si ça ne marche pas ?",
      "Ça me semble être une usine à gaz, non ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 3 phrases de la mélodie avec la vidéo, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "En réunion, reformulez une fois : « Si j'ai bien compris, … »."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute : expliquez un outil de votre travail, et envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "neuronale": "fr-FR-RemyMultilingualNeural",
    "dossiers": {
      "formateur": "audio/formateur/",
      "neuronale": "audio/neuronal/"
    }
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Choisissez le sujet pendant la discussion libre (champ « Mon sujet » : un outil ou une procédure de son travail). 1 minute, sans correction."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Parole spontanée très rapide (environ 191 mots/min). Faites deviner avant chaque écoute. Le passage difficile se réécoute seul."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Moitié « expliquer » (p1, p2, p6), moitié « vérifier » (p3, p4, p5). Faites adapter l'exemple au métier de l'apprenant."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Cible : la voix monte à la fin de chaque étape d'une explication ou d'une liste. Syllabes à cliquer, puis shadowing et courbes."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Vous jouez le collègue. À l'essai 2, lisez une question (« Question du collègue »). Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même sujet qu'au début. Commentez les 3 chiffres avec l'apprenant."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une réunion réelle, une date."
      }
    ],
    "notes": [
      "Vidéo : vraie conversation spontanée entre un journaliste d'Automobile Propre (Pierre) et le directeur technique de Chargemap. Hésitations, « euh », « du coup », « c'est pas » : de l'oral authentique.",
      "Extraits des phrases utiles : coupés dans des silences, puis retranscrits un par un avec deux modèles Whisper pour vérifier qu'aucun mot ne manque.",
      "Mélodie : les flèches viennent de mesures sur la voix réelle. Dans cette conversation, la question « …tu le fais une fois ? » ne monte pas à la fin : c'est pourquoi la cible n'est pas « la question monte », mais « la voix monte à chaque étape d'une explication » (nettement mesuré).",
      "La transcription automatique de YouTube écrit « Chargem Map », « ISO 1518 », « la FIR » : il faut lire Chargemap, ISO 15118 et AFIR (règlement européen).",
      "« C'est pas » (oral) et « ce n'est pas » (écrit, réunion formelle) : un bon point de discussion sur le registre."
    ]
  }
};
